#!/usr/bin/env bash
#
# bootstrap.sh — Sets up ONLY the local project.
#
# The local model provider (mistral-small-4-119b) is configured in opencode's
# system/global settings and is NOT installed, started, or managed by this script —
# that is intentionally out of scope for this project. This script only takes care
# of:
#   - npm dependencies for the Playwright custom tool (project-local)
#   - Playwright browsers (project-local, not in ~/.cache)
#   - Project configuration (base URL, login, secrets)
#
# Status: PLANNING DRAFT. Verify before real use (see TODO markers).
 
set -euo pipefail
 
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_DIR="$PROJECT_ROOT/.tools"
CONFIG_FILE="$PROJECT_ROOT/bootstrap.config"
TEST_PROPERTIES="$PROJECT_ROOT/config/test.properties"
SECRETS_FILE="$TOOLS_DIR/secrets.env"
 
echo "== AI Test Generator — Bootstrap (local project) =="
echo "Project folder: $PROJECT_ROOT"
echo "Note: The local model provider (mistral-small-4-119b) is configured in opencode's"
echo "system settings and is NOT set up here — see PLAN.md section 7."
echo
 
mkdir -p "$TOOLS_DIR" "$PROJECT_ROOT/config"
 
# ---------------------------------------------------------------------------
# 1. Project configuration: prefer a file, otherwise ask interactively
# ---------------------------------------------------------------------------
echo "[1/3] Project configuration ..."
 
if [ -f "$CONFIG_FILE" ]; then
  echo "    Using existing bootstrap.config as defaults."
  # shellcheck source=/dev/null
  source "$CONFIG_FILE"
else
  echo "    No bootstrap.config found — copying bootstrap.config.example as a template."
  if [ -f "$PROJECT_ROOT/bootstrap.config.example" ]; then
    cp "$PROJECT_ROOT/bootstrap.config.example" "$CONFIG_FILE.suggested"
    echo "    Template placed at bootstrap.config.suggested — rename to bootstrap.config"
    echo "    and fill it in if you'd like, then run bootstrap.sh again."
  fi
fi
 
if [ -z "${BASE_URL:-}" ]; then
  read -rp "    Base URL of the Angular/Oblique application: " BASE_URL
fi
if [ -z "${LOGIN_REQUIRED:-}" ]; then
  read -rp "    Does the application require a login? (y/n): " LOGIN_REQUIRED
fi
if [ "${LOGIN_REQUIRED:-n}" = "y" ] && [ -z "${TEST_USER:-}" ]; then
  read -rp "    Test username: " TEST_USER
fi
 
# Password NEVER goes into test.properties or bootstrap.config — only into the
# gitignored secrets file, with restrictive permissions. See PLAN.md section 6
# (secrets handling).
if [ "${LOGIN_REQUIRED:-n}" = "y" ]; then
  if [ -f "$SECRETS_FILE" ] && grep -q '^TEST_PASSWORD=' "$SECRETS_FILE" 2>/dev/null; then
    echo "    Test password already present in $SECRETS_FILE — skipping prompt."
  else
    read -rsp "    Test password (not shown, only stored in $SECRETS_FILE): " TEST_PASSWORD
    echo
    {
      echo "# Not versioned — see .gitignore. Generated by bootstrap.sh."
      echo "TEST_PASSWORD=${TEST_PASSWORD}"
    } > "$SECRETS_FILE"
    chmod 600 "$SECRETS_FILE"
    unset TEST_PASSWORD
    echo "    Password saved to $SECRETS_FILE (chmod 600, not versioned)."
  fi
fi
 
{
  echo "# Automatically generated by bootstrap.sh on $(date -u +%FT%TZ)"
  echo "base.url=${BASE_URL}"
  echo "login.required=${LOGIN_REQUIRED}"
  echo "test.user=${TEST_USER:-}"
  echo "# No password here! See .tools/secrets.env (PLAN.md section 6)."
} > "$TEST_PROPERTIES"

# ---------------------------------------------------------------------------
# 2. npm dependencies for the custom tool (project-local)
# ---------------------------------------------------------------------------
echo "[2/3] Installing npm dependencies (.opencode/) ..."
if [ -f "$PROJECT_ROOT/.opencode/package.json" ]; then
  (cd "$PROJECT_ROOT/.opencode" && npm install --no-audit --no-fund)
else
  echo "    !! .opencode/package.json doesn't exist yet — skipping this step."
  echo "       (see PLAN.md section 4.2 — custom tool not yet created)"
fi

# ---------------------------------------------------------------------------
# 3. Install Playwright browsers PROJECT-LOCAL (not in ~/.cache)
# ---------------------------------------------------------------------------
echo "[3/3] Installing Playwright browsers (project-local, not global) ..."
if [ -d "$PROJECT_ROOT/.opencode/node_modules/playwright" ] \
   || [ -d "$PROJECT_ROOT/.opencode/node_modules/playwright-core" ]; then
  (cd "$PROJECT_ROOT/.opencode" && PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install chromium)
else
  echo "    !! Playwright isn't listed in .opencode/package.json yet — skipping."
fi
 
echo
echo "== Bootstrap complete =="
echo "Installed locally: npm dependencies + Playwright browsers under"
echo "  $PROJECT_ROOT/.opencode/node_modules"
echo "No system changes made, no sudo used."
echo
echo "Configuration written to: $TEST_PROPERTIES"
echo "Local model provider: configured in opencode's system settings, not part of this script."
echo "Secrets (if login is required): $SECRETS_FILE"

